### ISSUE TITLE
Create your First Pull Request

### ISSUE THREAD

**Issue by rowhitswami** [rowhitswami/hacktoberfest19-first-timer#87]
Looking for contributing to Open-Source but confused and not finding the right way?
Congrats! You've landed on right place :smiley: 
Follow instruction in README.md and Create your First Pull Request :1st_place_medal:  out of 4 to earn a limited edition T-shirt from **Github** and **Digital Ocean** :heart:

**Comment by fineanmol** [comment]
Live page of Contributors. [Contributors](https://fineanmol.github.io/Hacktoberfest2k18/Contributors.html)
Don't forget to spread love and if you like to give us a ⭐️
